# Dublin postal district slugs and Daft v2 geoFilter storedShapeIds.
# Source: daftlistings location.py (AnthonyBloomer/daftlistings)

LOCATION_GEO_IDS = {
    "dublin-1-dublin": "65",
    "dublin-2-dublin": "66",
    "dublin-3-dublin": "67",
    "dublin-4-dublin": "68",
    "dublin-5-dublin": "69",
    "dublin-6-dublin": "70",
    "dublin-6w-dublin": "71",
    "dublin-7-dublin": "72",
    "dublin-8-dublin": "73",
    "dublin-9-dublin": "74",
    "dublin-10-dublin": "75",
    "dublin-11-dublin": "76",
    "dublin-12-dublin": "77",
    "dublin-13-dublin": "78",
    "dublin-14-dublin": "79",
    "dublin-15-dublin": "80",
    "dublin-16-dublin": "81",
    "dublin-17-dublin": "82",
    "dublin-18-dublin": "83",
    "dublin-20-dublin": "84",
    "dublin-22-dublin": "85",
    "dublin-24-dublin": "86",
}

LOCATION_OPTIONS = {
    "dublin-1-dublin": "Dublin 1",
    "dublin-2-dublin": "Dublin 2",
    "dublin-3-dublin": "Dublin 3",
    "dublin-4-dublin": "Dublin 4",
    "dublin-5-dublin": "Dublin 5",
    "dublin-6-dublin": "Dublin 6",
    "dublin-6w-dublin": "Dublin 6W",
    "dublin-7-dublin": "Dublin 7",
    "dublin-8-dublin": "Dublin 8",
    "dublin-9-dublin": "Dublin 9",
    "dublin-10-dublin": "Dublin 10",
    "dublin-11-dublin": "Dublin 11",
    "dublin-12-dublin": "Dublin 12",
    "dublin-13-dublin": "Dublin 13",
    "dublin-14-dublin": "Dublin 14",
    "dublin-15-dublin": "Dublin 15",
    "dublin-16-dublin": "Dublin 16",
    "dublin-17-dublin": "Dublin 17",
    "dublin-18-dublin": "Dublin 18",
    "dublin-20-dublin": "Dublin 20",
    "dublin-22-dublin": "Dublin 22",
    "dublin-24-dublin": "Dublin 24",
}
