services:
  - type: web
    name: daft-monitor-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPOSITORY
        sync: false
